name: hello-world
on:
 workflow_dispatch:
 push:
   branches:
     - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    environment:
      name: test-deployment
    steps:
      - name: my-step
        run: echo "Hello World!"
